@startuml
title Classes Diagram

Class Client
Class GuardList
Class ManagerSecurityAgency

Client"+" -> "+"ManagerSecurityAgency : review
Client"+" -up-> "+"GuardList : receive
ManagerSecurityAgency"1" -up-> "+"GuardList : provide
@enduml